### PR TITLE
Master Checklist for widgets

### PR DESCRIPTION
**Pull request by sandertyu**
Creating this PR for bookkeeping. All I've done is update some info about certain widgets in the README and add a big table which presents the status of each widget on each platform in a visually appealing way.

### CODE REVIEW

**Comment by moorepants** [comment]
Just to clarify: jupyterlab columns mean working with default-env on our hub? And do the thebe/cked/libre also meaning using our default env?

I think you need a column for thebe+package's binder image > example in thebe documentation. This shows that things can work if you have only thebe and a narrowed image with only the required packages for that particular row. Plus, I want you all adding examples to thebe's docs as a first step.

For libretexts.org, we have testing on query and on other libraries. I think all of the libraries may have different js/css installed. We've seen that these don't work sometimes in different libraries. So there should be at least a column for query (or first test) and one that signals *all* libraries on libretexts.org work.

**Comment by sandertyu** [comment]
> Just to clarify: jupyterlab columns mean working with default-env on our hub? And do the thebe/cked/libre also meaning using our default env?
> 
> I think you need a column for thebe+package's binder image > example in thebe documentation. This shows that things can work if you have only thebe and a narrowed image with only the required packages for that particular row. Plus, I want you all adding examples to thebe's docs as a first step.
> 
> For libretexts.org, we have testing on query and on other libraries. I think all of the libraries may have different js/css installed. We've seen that these don't work sometimes in different libraries. So there should be at least a column for query (or first test) and one that signals _all_ libraries on libretexts.org work.

Okay, I can add those. I'll add checklists signifying which versions of default-env have been tested as well as specifying query vs other libraries.

**Comment by sandertyu** [comment]
Thinking about this more, it seems like it could be confusing to put the environment in this master checklist. For instance, with ipywidgets, we've tested it on all platforms with default-env but it only works 100% in jupyterlab. This issue has nothing to do with our environment. To my knowledge, there has never been an issue with any widget due to the environment per se, only an issue with either Jupyterlab3 vs jupyterlab2 and their required jupyterlab extensions. 

If there is an issue with the environment, then we can put notes about it in the sections below. This table is just for a brief overview on the status on each widget.

**Comment by moorepants** [comment]
All of the example in thebe documentation use different environments and we had trouble with at least one. Whatever the table represents it needs to be clear what a check means in the column (to all of us, including me).

**Pull request merged**
